kind: KubeSchedulerConfiguration
apiVersion: kubescheduler.config.k8s.io/v1
profiles:
  - plugins:
      multiPoint:
        enabled:
          - name: wasm
          - name: NodeUnschedulable
    pluginConfig:
      - name: wasm
        args:
          guestURL: "file://../../../examples/nodeunschedulable/main.wasm"
extenders:
  - urlPrefix: "http://localhost:8080/"
    prioritizeVerb: "priorities"
    weight: 1
    enableHTTPS: false
    nodeCacheCapable: false